### ISSUE TITLE
BadImageFormatException on Blinkie ARM64

### ISSUE THREAD

**Issue by Daniel127** [StanDeMan/RaspberryDebugger#8]
I am trying to test the Demo but I get this error after successfully connecting and installing the SDK, upload the application correctly and then:

> An unhandled exception of type 'System.BadImageFormatException' occurred in Unknown Module.: 'Could not load file or assembly '/home/pi/vsdbg/Blinkie/Blinkie.dll'. An attempt was made to load a program with an incorrect format.'

I have changed the version of `Blinkie.csproj` for using .NET 6 and line 259 of `ProjectProperties.cs` to this one, so it will not throw an exception for the architecture.

`PackageHelper.SdkCatalog.Items.SingleOrDefault(item=> SemanticVersion.Parse(item.Name) == SemanticVersion.Parse(sdkName) && item.Architecture == targetSdk.Architecture);` 

RASPBERRY INFO:
[raspberry]: INFO: [pi@raspberrypi]: Verify Connection
[raspberry]: INFO: DNS lookup for: raspberrypi
[raspberry]: INFO: [raspberrypi]: Auth via SSH keys
[raspberry]: INFO: [raspberrypi]: Checking for: [unzip]
[raspberry]: INFO: [raspberrypi]: Retrieving status
[raspberry]: INFO: [raspberrypi]: Fetching status
[raspberry]: INFO: [raspberrypi]: processor: aarch64
[raspberry]: INFO: [raspberrypi]: path:      /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
[raspberry]: INFO: [raspberrypi]: unzip:     True
[raspberry]: INFO: [raspberrypi]: debugger:  True
[raspberry]: INFO: [raspberrypi]: sdks:      6.0.100, 6.0.202
[raspberry]: INFO: [raspberrypi]: model:     Raspberry Pi Zero 2 W Rev 1.0
[raspberry]: INFO: [raspberrypi]: revision:  902120
[raspberry]: WARNING: [raspberrypi]: .NET SDK [6.0.100] is present on [raspberrypi] but is not known to the RaspberryDebugger extension. Consider updating the extension.

**Comment by StanDeMan** [comment]
@Daniel127 Thanks a lot for your feedback.
Was working till yesterday to get 64 Bit working - still not finished. Have to test more...
There seems to be a missmatch - the used .NET version is not known to the debugger. Don't know why?
Delete the dotnet folder underneath /usr/lib completly with "sudo rm -r dotnet". The debugger should take the actual .NET package if you deploy again.  Raspberry Pi Zero 2 W Rev 1.0 (500MB memory only) is pretty constrained. Take a Pi 4 Modell B with 4 or 8GB for development. Later you can deploy your stuff to Pi Zero 2W.

**Comment by Daniel127** [comment]
Hello @StanDeMan ,

Thanks for your work, I have updated to the latest commit and I have been able to run and debug the Blinkie console project without problems from the Raspberry Pi Zero 2 64Bits.

However with the web project I have a problem that I don't understand, I have added this to the csproj to be able to run it: `<PlatformTarget>AnyCPU</PlatformTarget>`
`<SignAssembly>True</SignAssembly>`

Apparently it starts correctly and I see it in the Output.
![imagen](https://user-images.githubusercontent.com/9024993/176969209-71d2e61b-2bdc-48b6-801b-b8058b7b7139.png)

But after a while I get an exception and it ends up closing visual studio with the debugger.
![imagen](https://user-images.githubusercontent.com/9024993/176966310-bdecacc8-6ec3-4d8a-b916-aed0d7c45881.png)

Do you know what it can be?

Again thanks for all the work, I hope that soon this a final version and can install it from the marketplace

**Comment by StanDeMan** [comment]
Hi Daniel127,
glad to read that you got it running. So the scraping service I deployed to Azure is working. :)
Even glad to read that 64Bit is running so well on an Pi Zero2 - having so less memory.
I deploy a new debugger version to nuget asap.

Please add to your ASP.NET project this attributes:
<RuntimeIdentifier>linux-arm</RuntimeIdentifier>
<PlatformTarget>AnyCPU</PlatformTarget> 
Runtimeidentifier (linux-arm) is essential. No need to sign assemblies. Put them under: <PropertyGroup>

As far as I know you cannot debug ASP.NET projects without having an working Web Server (as proxy) configured.
I think you are running in a timeout - the debugger is not reaching your deplyoment to the raspi.
I'm using NGiNX. Here you can find a great example how to configure the web server:
https://setu677.medium.com/how-to-host-asp-net-core-on-linux-using-nginx-85339560e929
Helped me quite a lot.

Try to run your ASP.NET directly under the pi/home/vsdbg/yourStuff??? folder with: sudo dotnet yourStuff???.dll
If you can start it - the deployment was successful - but the debugger isn't able to reach your service.
You should be able to access your page locally on the pi under http://127.0.0.1:5000
If you want to access from other computer configure a web-server - as Setu Kumar Basak is described underneath chapter 2.1 and below.

Hope it helps.

Kindest regards
StanDeMan

**Comment by Daniel127** [comment]
Hello @StanDeMan 

I have been doing some tests, I understand what you say about using nginx as a proxy but I think it should be something optional and chosen by each developer, in a development environment and quick testing may be unnecessary.

I have created a PR #10 with the changes I made to run a WebApi and access it from my PC, the main thing is the environment variable `ASPNETCORE_URLS`, it specifies that it can be accessed from outside and not only from the local environment, I had to change the `appListeningScript` so it could return 0 and not throw any exception.

There are some things that I don't understand why they were like that, like the `baseuri` with ".local" at the end, or the way in which I assigned the variable IsAspNet, why I was looking for IIS configuration? if in linux only the Kestrel server works.

As I said before the PR is the result of testing until I got the result I wanted, surely it can be done better and more configurable, for example for those who want to start the app and allow only local connections (from the raspberry) or even not to fail to parse `applicationUrl` by having several separated with ";".

What do you think about these changes?

**Comment by StanDeMan** [comment]
Dear Daniel127,

thanks a lot for your pull request and the changes you did.

Every raspberry pi os is configured to work with Avahi/ZeroConf/Bonjour/mDNS using the .local Domain. There is no need to handle with IP addresses or ports. The raspberry pi is accessable via given http://raspberrypiname.local out of the box - even if ip addresses are changing - the raspberrypiname.local gets found. This is handeled by mDNS/Avahi. This is great, because it's working out of the box. Was developed by Appel and ported to linux and windows.

The IIS configuration is inside because it's crossplatform. I develop often locally on my pc - sometimes using IIS. Why not? The configuration is used, if I do so. If you don't need it - throw it away. This has nothing to do with the debugger. It's configuration. I'm working mostly with multipe platforms.

Maybe I can use your changes with avahi, too. Have to see? Avahi isn't aware about ports. No need for them.

Kindest regards
StanDeMan

**Comment by StanDeMan** [comment]
Dear Daniel127,

thanks for your hint. 
Add the 'Microsoft.Extensions.Hosting.Systemd' ([nuget (https://www.nuget.org/packages/Microsoft.Extensions.Hosting.Systemd/)) package with `dotnet add package Microsoft.Extensions.Hosting.Systemd` to your project of the waether service example. 
`var builder = WebApplication.CreateBuilder(args);`
`builder.Host.UseSystemd() //add this to your code;`

Take the latest sources of the debugger. I corrected an error opening the browser - maybe caused by me - maybe no one was aware about it? The sources should be deployed now to raspberry pi using raspberrypiname.local and starting directly swagger - taking Kestrel as reverse proxy. This is dependant on your configuration and what you want to achieve. Whaterever you want should be possible.
I prefer to use a web server as reverse proxy which can deal with certificates and other important stuff.

Good luck.

Kindest regards
StanDeMan

**Comment by StanDeMan** [comment]
Was fixed by commit: https://github.com/StanDeMan/RaspberryDebugger/commit/fc52741c2a5301760b399ef09b9a673e15e8540f

**Comment by StanDeMan** [comment]
Dear Daniel127,

the last step I plan to do is to have the Kestrel option better implemented.
Kestrel is working if you put this code into your sources:
```
var builder = WebApplication.CreateBuilder(args);
builder.Host.UseSystemd();
// Kestrel configuration to get working with debugger
builder.WebHost.ConfigureKestrel(options =>
{
    options.ListenAnyIP(5000);
    options.ListenAnyIP(5001, configure => configure.UseHttps()); // to listen for incoming https connection on port 5001
});

After the deployment you have to start the browser at your own:
`https://YourRaspiIPAddress:5001/swagger/index.html`
Maybe I can start the browser automatically to get it better integrated. Have to see...

Thanks for the hint.

Kindest regards
StanDeMan
